# Grunt aliases
---
# Build everything
build:
  - 'build:js'
  - 'build:i18n'

'build-watch':
  - 'shell:composer-install'
  - 'build:js'
  - 'watch'

# Build JavaScript from assets to production
'build:js':
  - 'clean:build-assets-js'
  - 'webpack:buildDev'

# Build internationalisation features
'build:i18n':
  - 'addtextdomain'
  - 'clean:language-files'
  - 'build:i18n:potFiles'
  - 'build:i18n:translations'
  - 'clean:after-build-language-files'
# Create the relevant POT files and combine to one
'build:i18n:potFiles':
  - 'makepot'
  - 'shell:makepot-wordpress-seo-news'
  - 'copy:makepot-wordpress-seo-news'
  - 'shell:combine-pot-files'
# Download and build the latest translations: MO for PHP and JSON for JS
'build:i18n:translations':
  - 'glotpress_download'
  - 'copy:json-translations'
  - 'po2json'
  - 'i18n-clean-json'

# Create a zipped artifact from a fresh build
'artifact':
  - 'shell:composer-install-production'
  - 'update-version'
  - 'release'
  - 'clean:artifact'
  - 'copy:artifact'
  - 'compress:artifact'
  - 'shell:composer-install-dev'

# Default task
default:
  - build

# Get the project ready for release
release:
  - 'release:js'
  - 'build:i18n'

'release:js':
  - 'clean:build-assets-js'
  - 'webpack:buildProd'
